# Generated by Django 2.2.28 on 2023-01-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('gender', models.TextField(primary_key=True, serialize=False)),
                ('race_ethnicity', models.TextField(blank=True, db_column='race/ethnicity', null=True)),
                ('parental_level_of_education', models.TextField(blank=True, db_column='parental level of education', null=True)),
                ('lunch', models.TextField(blank=True, null=True)),
                ('test_preparation_course', models.TextField(blank=True, db_column='test preparation course', null=True)),
                ('math_score', models.TextField(blank=True, db_column='math score', null=True)),
                ('reading_score', models.TextField(blank=True, db_column='reading score', null=True)),
                ('writing_score', models.TextField(blank=True, db_column='writing score', null=True)),
            ],
            options={
                'db_table': 'student_performance',
                'managed': False,
            },
        ),
    ]
